#include <catch2/catch_all.hpp>
#include <cfenv>

#include "quadruple.hpp"
#include "test_helpers/test_utils.hpp"
#include "utils.hpp"
#include <cstring>
#include <numbers>

#if defined(IMPLICIT_CASTS)
constexpr bool implicit_conversion_allowed = true;
#else
constexpr bool implicit_conversion_allowed = false;
#endif

TEMPLATE_LIST_TEST_CASE("implicit conversion", "[conversion]", all_constructable_types) {
    STATIC_REQUIRE(std::is_convertible_v<TestType, quadruple> == implicit_conversion_allowed);
}

TEMPLATE_TEST_CASE("same type conversion", "[conversion][floating]", float, double) {
    auto check_conversion = [](TestType val) {
        quadruple val_converted{val};
        // no values generated by float/double constructors should be considered
        // subnormal for quadruple
        REQUIRE(!val_converted.is_subnormal());
        TestType converted_back{val_converted};
        // compare bits
        REQUIRE(std::memcmp(&val, &converted_back, sizeof(TestType)) == 0);
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(TestType{}); }
            SECTION("one") { check_conversion(TestType{1}); }
            SECTION("pi") { check_conversion(std::numbers::pi_v<TestType>); }
            SECTION("e") { check_conversion(std::numbers::e_v<TestType>); }
            SECTION("phi") { check_conversion(std::numbers::phi_v<TestType>); }
            SECTION("sqrt2") { check_conversion(std::numbers::sqrt2_v<TestType>); }
            SECTION("sqrt3") { check_conversion(std::numbers::sqrt3_v<TestType>); }
            SECTION("inv_sqrtpi") { check_conversion(std::numbers::inv_sqrtpi_v<TestType>); }
            SECTION("infinity") { check_conversion(std::numeric_limits<TestType>::infinity()); }
            SECTION("qNaN") { check_conversion(std::numeric_limits<TestType>::quiet_NaN()); }
            SECTION("sNaN") { check_conversion(std::numeric_limits<TestType>::signaling_NaN()); }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(-TestType{}); }
            SECTION("one") { check_conversion(-TestType{1}); }
            SECTION("pi") { check_conversion(-std::numbers::pi_v<TestType>); }
            SECTION("e") { check_conversion(-std::numbers::e_v<TestType>); }
            SECTION("phi") { check_conversion(-std::numbers::phi_v<TestType>); }
            SECTION("sqrt2") { check_conversion(-std::numbers::sqrt2_v<TestType>); }
            SECTION("sqrt3") { check_conversion(-std::numbers::sqrt3_v<TestType>); }
            SECTION("inv_sqrtpi") { check_conversion(-std::numbers::inv_sqrtpi_v<TestType>); }
            SECTION("infinity") { check_conversion(-std::numeric_limits<TestType>::infinity()); }
            SECTION("qNaN") { check_conversion(-std::numeric_limits<TestType>::quiet_NaN()); }
            SECTION("sNaN") { check_conversion(negative_sNaN<TestType>()); }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

TEMPLATE_TEST_CASE_SIG("different type conversion",
                       "[conversion][floating]",
                       ((typename FromType, typename ToType), FromType, ToType),
                       (float, double),
                       (double, float)) {
    auto check_conversion = [](FromType val) {
        quadruple val_converted{val};
        // no values generated by float/double constructors should be considered
        // subnormal for quadruple
        REQUIRE(!val_converted.is_subnormal());
        auto converted = static_cast<ToType>(val);
        auto double_converted = static_cast<ToType>(val_converted);
        // compare bits
        if (std::memcmp(&converted, &double_converted, sizeof(converted)) != 0) {
            auto double_converted_again = static_cast<ToType>(quadruple{val});
            REQUIRE(std::memcmp(&converted, &double_converted_again, sizeof(converted)) == 0);
        }
        REQUIRE(std::memcmp(&converted, &double_converted, sizeof(converted)) == 0);
    };
    // static_cast float::sNaN to double != double::sNaN
    auto check_NaN_conversion = [](FromType val) {
        REQUIRE(std::isnan(val));
        quadruple val_converted{val};
        ToType converted;
        if (is_qNaN(val)) {
            converted = std::numeric_limits<ToType>::quiet_NaN();
        } else if (is_sNaN(val)) {
            converted = std::numeric_limits<ToType>::signaling_NaN();
        } else {
            REQUIRE(false);
        }
        if (std::signbit(val)) {
            // Bitflip sign, to avoid triggering possible sNaN checks
            if constexpr (sizeof(ToType) == sizeof(uint32_t)) {
                converted = std::bit_cast<ToType>(std::bit_cast<uint32_t>(converted) ^ single_bit_mask<uint32_t, 0>());
            } else if (sizeof(ToType) == sizeof(uint64_t)) {
                converted = std::bit_cast<ToType>(std::bit_cast<uint64_t>(converted) ^ single_bit_mask<uint64_t, 0>());
            } else {
                REQUIRE(false);
            }
        }
        auto double_converted = static_cast<ToType>(val_converted);
        // compare bits
        REQUIRE(std::memcmp(&converted, &double_converted, sizeof(converted)) == 0);
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(FromType{}); }
            SECTION("one") { check_conversion(FromType{1}); }
            SECTION("pi") { check_conversion(std::numbers::pi_v<FromType>); }
            SECTION("e") { check_conversion(std::numbers::e_v<FromType>); }
            SECTION("phi") { check_conversion(std::numbers::phi_v<FromType>); }
            SECTION("sqrt2") { check_conversion(std::numbers::sqrt2_v<FromType>); }
            SECTION("sqrt3") { check_conversion(std::numbers::sqrt3_v<FromType>); }
            SECTION("inv_sqrt(pi)") { check_conversion(std::numbers::inv_sqrtpi_v<FromType>); }
            SECTION("infinity") { check_conversion(std::numeric_limits<FromType>::infinity()); }
            SECTION("qNaN") { check_NaN_conversion(std::numeric_limits<FromType>::quiet_NaN()); }
            SECTION("sNaN") { check_NaN_conversion(std::numeric_limits<FromType>::signaling_NaN()); }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<FromType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<FromType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(-FromType{}); }
            SECTION("one") { check_conversion(-FromType{1}); }
            SECTION("pi") { check_conversion(-std::numbers::pi_v<FromType>); }
            SECTION("e") { check_conversion(-std::numbers::e_v<FromType>); }
            SECTION("phi") { check_conversion(-std::numbers::phi_v<FromType>); }
            SECTION("sqrt2") { check_conversion(-std::numbers::sqrt2_v<FromType>); }
            SECTION("sqrt3") { check_conversion(-std::numbers::sqrt3_v<FromType>); }
            SECTION("inv_sqrt(pi)") { check_conversion(-std::numbers::inv_sqrtpi_v<FromType>); }
            SECTION("infinity") { check_conversion(-std::numeric_limits<FromType>::infinity()); }
            SECTION("qNaN") { check_NaN_conversion(-std::numeric_limits<FromType>::quiet_NaN()); }
            SECTION("sNaN") { check_NaN_conversion(negative_sNaN<FromType>()); }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<FromType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<FromType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

TEMPLATE_TEST_CASE("from quadruple subnormals", "[conversion][floating]", float, double) {
    auto check_conversion = [](quadruple val) {
        TestType converted{val};
        REQUIRE(std::fpclassify(converted) == FP_ZERO);
    };

    auto generated = generate_subnormal_numbers<quadruple>(test_size);

    SECTION("positive") {
        for (auto val : generated) {
            check_conversion(val);
        }
    }

    SECTION("negative") {
        for (auto val : generated) {
            check_conversion(-val);
        }
    }
}

template<typename T>
constexpr bool check_representation([[maybe_unused]] T val) {
#if defined(EXTENSIONS) && defined(__SIZEOF_INT128__)
    if constexpr (sizeof(T) * 8 > quadruple_mantissa_size) {
        if constexpr (std::is_same_v<T, __int128>) {
            return val <= max_representable_int128 && val >= min_representable_int128;
        } else if constexpr (std::is_same_v<T, unsigned __int128>) {
            return val <= max_representable_uint128;
        }
    }
#endif
    return true;
}

TEMPLATE_LIST_TEST_CASE("same type conversion", "[conversion][integers]", integer_types) {
    auto check_conversion = [](TestType val) {
        if (check_representation(val)) {
            quadruple val_converted{val};
            TestType converted_back{val_converted};
            REQUIRE(val == converted_back);
        } else {
            // edge case of 128 bit integers
            // not every number can be represented in quadruple exactly, but after
            // rounding it can be if value is less than 'quadruple_mantissa_size' bits
            // than val_converted and val_converted_rounded will be the same
            quadruple val_converted_rounded{val};
            TestType converted_back_rounded{val_converted_rounded};
            quadruple val_converted{converted_back_rounded};
            TestType converted_back{val_converted};
            REQUIRE(converted_back_rounded == converted_back);
        }
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(TestType{}); }
            SECTION("one") { check_conversion(TestType{1}); }
            SECTION("five") { check_conversion(TestType{5}); }
            SECTION("hundred") { check_conversion(TestType{100}); }
            if constexpr (sizeof(TestType) == 8) {
                SECTION("2^50") { check_conversion(static_cast<TestType>(TestType{1} << 49)); }
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") { check_conversion(static_cast<TestType>(-TestType{})); }
            SECTION("one") { check_conversion(static_cast<TestType>(-TestType{1})); }
            SECTION("five") { check_conversion(static_cast<TestType>(-TestType{5})); }
            SECTION("hundred") { check_conversion(static_cast<TestType>(-TestType{100})); }
            if constexpr (sizeof(TestType) == 8) {
                SECTION("2^50") { check_conversion(-(static_cast<TestType>(TestType{1} << 49))); }
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

using rounding_conversion_types = types_cross_product<std::tuple<float, double>, integer_types>::type;

// list does not work with signatures
TEMPLATE_LIST_TEST_CASE("rounding conversion", "[conversion][integers]", rounding_conversion_types) {
    using FromType = std::tuple_element<0, TestType>::type;
    using ToType = std::tuple_element<1, TestType>::type;
    auto check_conversion = [](FromType original_val, bool should_raise = false) {
        quadruple quad{original_val};
        ToType converted1 = static_cast<ToType>(original_val);
        std::feclearexcept(FE_ALL_EXCEPT);
        ToType converted2{quad};
        REQUIRE(std::fetestexcept(FE_INVALID) == should_raise);

        // for some reason, without using both variables REQUIRE fails sometimes in
        // Release build
        CAPTURE(converted1);
        CAPTURE(converted2);
        REQUIRE(converted1 == converted2);
    };

    SECTION("positive") {
        SECTION("0.49") { check_conversion(static_cast<FromType>(0.49)); }
        SECTION("0.5") { check_conversion(static_cast<FromType>(0.50)); }
        SECTION("0.51") { check_conversion(static_cast<FromType>(0.51)); }
        SECTION("1.49") { check_conversion(static_cast<FromType>(1.49)); }
        SECTION("1.50") { check_conversion(static_cast<FromType>(1.50)); }
        SECTION("1.51") { check_conversion(static_cast<FromType>(1.51)); }
        SECTION("2.49") { check_conversion(static_cast<FromType>(2.49)); }
        SECTION("2.50") { check_conversion(static_cast<FromType>(2.50)); }
        SECTION("2.51") { check_conversion(static_cast<FromType>(2.51)); }
        SECTION("1e7") { check_conversion(static_cast<FromType>(1e7)); }
        SECTION("1e8") { check_conversion(static_cast<FromType>(1e8)); }
        SECTION("1e9") { check_conversion(static_cast<FromType>(1e9)); }
        SECTION("1e10") { check_conversion(static_cast<FromType>(1e10)); }
        SECTION("1e11") { check_conversion(static_cast<FromType>(1e11)); }
        SECTION("1e12") { check_conversion(static_cast<FromType>(1e12)); }
        SECTION("1e13") { check_conversion(static_cast<FromType>(1e13)); }
        SECTION("1e14") { check_conversion(static_cast<FromType>(1e14)); }
        SECTION("1e15") { check_conversion(static_cast<FromType>(1e15)); }
        SECTION("1e16") { check_conversion(static_cast<FromType>(1e16)); }
        SECTION("1e17") { check_conversion(static_cast<FromType>(1e17)); }
        SECTION("1e18") { check_conversion(static_cast<FromType>(1e18)); }
        SECTION("1e19") { check_conversion(static_cast<FromType>(1e19)); }
        SECTION("1e20") { check_conversion(static_cast<FromType>(1e20)); }
        SECTION("1e21") { check_conversion(static_cast<FromType>(1e21)); }
        SECTION("1e30") { check_conversion(static_cast<FromType>(1e30)); }
        if constexpr (sizeof(FromType) == sizeof(double)) {
            SECTION("1e70") { check_conversion(static_cast<FromType>(1e70)); }
        }
        SECTION("Inf") { check_conversion(std::numeric_limits<FromType>::infinity(), true); }
        SECTION("NaN") { check_conversion(std::numeric_limits<FromType>::quiet_NaN(), true); }
    }

    SECTION("negative") {
        SECTION("0.49") { check_conversion(static_cast<FromType>(-0.49)); }
        SECTION("0.5") { check_conversion(static_cast<FromType>(-0.50)); }
        SECTION("0.51") { check_conversion(static_cast<FromType>(-0.51)); }
        SECTION("1.49") { check_conversion(static_cast<FromType>(-1.49)); }
        SECTION("1.50") { check_conversion(static_cast<FromType>(-1.50)); }
        SECTION("1.51") { check_conversion(static_cast<FromType>(-1.51)); }
        SECTION("2.49") { check_conversion(static_cast<FromType>(-2.49)); }
        SECTION("2.50") { check_conversion(static_cast<FromType>(-2.50)); }
        SECTION("2.51") { check_conversion(static_cast<FromType>(-2.51)); }
        SECTION("1e7") { check_conversion(static_cast<FromType>(-1e7)); }
        SECTION("1e8") { check_conversion(static_cast<FromType>(-1e8)); }
        SECTION("1e9") { check_conversion(static_cast<FromType>(-1e9)); }
        SECTION("1e10") { check_conversion(static_cast<FromType>(-1e10)); }
        SECTION("1e11") { check_conversion(static_cast<FromType>(-1e11)); }
        SECTION("1e12") { check_conversion(static_cast<FromType>(-1e12)); }
        SECTION("1e13") { check_conversion(static_cast<FromType>(-1e13)); }
        SECTION("1e14") { check_conversion(static_cast<FromType>(-1e14)); }
        SECTION("1e15") { check_conversion(static_cast<FromType>(-1e15)); }
        SECTION("1e16") { check_conversion(static_cast<FromType>(-1e16)); }
        SECTION("1e17") { check_conversion(static_cast<FromType>(-1e17)); }
        SECTION("1e18") { check_conversion(static_cast<FromType>(-1e18)); }
        SECTION("1e19") { check_conversion(static_cast<FromType>(-1e19)); }
        SECTION("1e20") { check_conversion(static_cast<FromType>(-1e20)); }
        SECTION("1e21") { check_conversion(static_cast<FromType>(-1e21)); }
        SECTION("1e30") { check_conversion(static_cast<FromType>(-1e30)); }
        if constexpr (sizeof(FromType) == sizeof(double)) {
            SECTION("1e70") { check_conversion(static_cast<FromType>(-1e70)); }
        }
        SECTION("Inf") { check_conversion(-std::numeric_limits<FromType>::infinity(), true); }
        SECTION("NaN") { check_conversion(-std::numeric_limits<FromType>::quiet_NaN(), true); }
    }
}
