#include <cfenv>
#include <catch2/catch_all.hpp>

#include "quadruple.hpp"
#include "utils.hpp"
#include "test_helpers/test_utils.hpp"
#include <cstring>
#include <numbers>

TEMPLATE_TEST_CASE("same type conversion", "[conversion][floating]", float, double) {
    auto check_conversion = [](TestType val) {
        quadruple val_converted{val};
        // no values generated by float/double constructors should be considered subnormal for quadruple
        REQUIRE(!val_converted.is_subnormal());
        TestType converted_back{val_converted};
        // compare bits
        REQUIRE(std::memcmp(&val, &converted_back, sizeof(TestType)) == 0);
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(TestType{});
            }
            SECTION("one") {
                check_conversion(TestType{1});
            }
            SECTION("pi") {
                check_conversion(std::numbers::pi_v<TestType>);
            }
            SECTION("e") {
                check_conversion(std::numbers::e_v<TestType>);
            }
            SECTION("phi") {
                check_conversion(std::numbers::phi_v<TestType>);
            }
            SECTION("sqrt2") {
                check_conversion(std::numbers::sqrt2_v<TestType>);
            }
            SECTION("sqrt3") {
                check_conversion(std::numbers::sqrt3_v<TestType>);
            }
            SECTION("inv_sqrtpi") {
                check_conversion(std::numbers::inv_sqrtpi_v<TestType>);
            }
            SECTION("infinity") {
                check_conversion(std::numeric_limits<TestType>::infinity());
            }
            SECTION("qNaN") {
                check_conversion(std::numeric_limits<TestType>::quiet_NaN());
            }
            SECTION("sNaN") {
                check_conversion(std::numeric_limits<TestType>::signaling_NaN());
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(-TestType{});
            }
            SECTION("one") {
                check_conversion(-TestType{1});
            }
            SECTION("pi") {
                check_conversion(-std::numbers::pi_v<TestType>);
            }
            SECTION("e") {
                check_conversion(-std::numbers::e_v<TestType>);
            }
            SECTION("phi") {
                check_conversion(-std::numbers::phi_v<TestType>);
            }
            SECTION("sqrt2") {
                check_conversion(-std::numbers::sqrt2_v<TestType>);
            }
            SECTION("sqrt3") {
                check_conversion(-std::numbers::sqrt3_v<TestType>);
            }
            SECTION("inv_sqrtpi") {
                check_conversion(-std::numbers::inv_sqrtpi_v<TestType>);
            }
            SECTION("infinity") {
                check_conversion(-std::numeric_limits<TestType>::infinity());
            }
            SECTION("qNaN") {
                check_conversion(-std::numeric_limits<TestType>::quiet_NaN());
            }
            SECTION("sNaN") {
                check_conversion(negative_sNaN<TestType>());
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

TEMPLATE_TEST_CASE_SIG("different type conversion", "[conversion][floating]",
    ((typename FromType, typename ToType), FromType, ToType), (float, double), (double, float)) {
    auto check_conversion = [](FromType val) {
        quadruple val_converted{val};
        // no values generated by float/double constructors should be considered subnormal for quadruple
        REQUIRE(!val_converted.is_subnormal());
        auto converted = static_cast<ToType>(val);
        auto double_converted = static_cast<ToType>(val_converted);
        // compare bits
        if (std::memcmp(&converted, &double_converted, sizeof(converted)) != 0) {
            auto double_converted_again = static_cast<ToType>(quadruple{val});
            REQUIRE(std::memcmp(&converted, &double_converted_again, sizeof(converted)) == 0);
        }
        REQUIRE(std::memcmp(&converted, &double_converted, sizeof(converted)) == 0);
    };
    // static_cast float::sNaN to double != double::sNaN
    auto check_NaN_conversion = [](FromType val) {
        REQUIRE(std::isnan(val));
        quadruple val_converted{val};
        ToType converted;
        if (is_qNaN(val)) {
            converted = std::numeric_limits<ToType>::quiet_NaN();
        } else if (is_sNaN(val)) {
            converted = std::numeric_limits<ToType>::signaling_NaN();
        } else {
            REQUIRE(false);
        }
        if (std::signbit(val)) {
            // Bitflip sign, to avoid triggering possible sNaN checks
            if constexpr (sizeof(ToType) == sizeof(uint32_t)) {
                converted = std::bit_cast<ToType>(std::bit_cast<uint32_t>(converted) ^ single_bit_mask<uint32_t, 0>());
            } else if (sizeof(ToType) == sizeof(uint64_t)) {
                converted = std::bit_cast<ToType>(std::bit_cast<uint64_t>(converted) ^ single_bit_mask<uint64_t, 0>());
            } else {
                REQUIRE(false);
            }
        }
        auto double_converted = static_cast<ToType>(val_converted);
        // compare bits
        REQUIRE(std::memcmp(&converted, &double_converted, sizeof(converted)) == 0);
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(FromType{});
            }
            SECTION("one") {
                check_conversion(FromType{1});
            }
            SECTION("pi") {
                check_conversion(std::numbers::pi_v<FromType>);
            }
            SECTION("e") {
                check_conversion(std::numbers::e_v<FromType>);
            }
            SECTION("phi") {
                check_conversion(std::numbers::phi_v<FromType>);
            }
            SECTION("sqrt2") {
                check_conversion(std::numbers::sqrt2_v<FromType>);
            }
            SECTION("sqrt3") {
                check_conversion(std::numbers::sqrt3_v<FromType>);
            }
            SECTION("inv_sqrt(pi)") {
                check_conversion(std::numbers::inv_sqrtpi_v<FromType>);
            }
            SECTION("infinity") {
                check_conversion(std::numeric_limits<FromType>::infinity());
            }
            SECTION("qNaN") {
                check_NaN_conversion(std::numeric_limits<FromType>::quiet_NaN());
            }
            SECTION("sNaN") {
                check_NaN_conversion(std::numeric_limits<FromType>::signaling_NaN());
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<FromType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<FromType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(-FromType{});
            }
            SECTION("one") {
                check_conversion(-FromType{1});
            }
            SECTION("pi") {
                check_conversion(-std::numbers::pi_v<FromType>);
            }
            SECTION("e") {
                check_conversion(-std::numbers::e_v<FromType>);
            }
            SECTION("phi") {
                check_conversion(-std::numbers::phi_v<FromType>);
            }
            SECTION("sqrt2") {
                check_conversion(-std::numbers::sqrt2_v<FromType>);
            }
            SECTION("sqrt3") {
                check_conversion(-std::numbers::sqrt3_v<FromType>);
            }
            SECTION("inv_sqrt(pi)") {
                check_conversion(-std::numbers::inv_sqrtpi_v<FromType>);
            }
            SECTION("infinity") {
                check_conversion(-std::numeric_limits<FromType>::infinity());
            }
            SECTION("qNaN") {
                check_NaN_conversion(-std::numeric_limits<FromType>::quiet_NaN());
            }
            SECTION("sNaN") {
                check_NaN_conversion(negative_sNaN<FromType>());
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<FromType>(test_size);
            remove_NaNs(generated);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
        SECTION("random subnormal numbers") {
            auto generated = generate_subnormal_numbers<FromType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

TEMPLATE_TEST_CASE("from quadruple subnormals", "[conversion][floating]", float, double) {
    auto check_conversion = [](quadruple val) {
        TestType converted{val};
        REQUIRE(std::fpclassify(converted) == FP_ZERO);
    };

    auto generated = generate_subnormal_numbers<quadruple>(test_size);

    SECTION("positive") {
        for (auto val : generated) {
            check_conversion(val);
        }
    }

    SECTION("negative") {
        for (auto val : generated) {
            check_conversion(-val);
        }
    }
}

TEMPLATE_TEST_CASE("same type conversion", "[conversion][integers]",
    int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t) {
    auto check_conversion = [](TestType val) {
        quadruple val_converted{val};
        TestType converted_back{val_converted};
        REQUIRE(val == converted_back);
    };

    SECTION("positive") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(TestType{});
            }
            SECTION("one") {
                check_conversion(TestType{1});
            }
            SECTION("five") {
                check_conversion(TestType{5});
            }
            SECTION("hundred") {
                check_conversion(TestType{100});
            }
            if constexpr (sizeof(TestType) == 8) {
                SECTION("2^50") {
                    check_conversion(static_cast<TestType>(TestType{1} << 49));
                }
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(value);
            }
        }
    }

    SECTION("negative") {
        SECTION("constants") {
            SECTION("zero") {
                check_conversion(static_cast<TestType>(-TestType{}));
            }
            SECTION("one") {
                check_conversion(static_cast<TestType>(-TestType{1}));
            }
            SECTION("five") {
                check_conversion(static_cast<TestType>(-TestType{5}));
            }
            SECTION("hundred") {
                check_conversion(static_cast<TestType>(-TestType{100}));
            }
            if constexpr (sizeof(TestType) == 8) {
                SECTION("2^50") {
                    check_conversion(-(static_cast<TestType>(TestType{1} << 49)));
                }
            }
        }
        SECTION("random numbers") {
            auto generated = generate_normal_numbers<TestType>(test_size);
            for (auto value : generated) {
                check_conversion(-value);
            }
        }
    }
}

TEMPLATE_TEST_CASE_SIG("rounding conversion", "[conversion][integers]",
    ((typename FromType, typename ToType), FromType, ToType),
    (double, int8_t),
    (double, int16_t),
    (double, int32_t),
    (double, int64_t),
    (double, uint8_t),
    (double, uint16_t),
    (double, uint32_t),
    (double, uint64_t)) {
    auto check_conversion = [](FromType original_val, bool should_raise = false) {
        quadruple quad{original_val};
        ToType converted1 = static_cast<ToType>(original_val);
        std::feclearexcept(FE_ALL_EXCEPT);
        ToType converted2{quad};
        REQUIRE(std::fetestexcept(FE_INVALID) == should_raise);

        REQUIRE(converted1 == converted2);
    };

    SECTION("positive") {
        SECTION("0.49") {
            check_conversion(0.49);
        }
        SECTION("0.5") {
            check_conversion(0.50);
        }
        SECTION("0.51") {
            check_conversion(0.51);
        }
        SECTION("1.49") {
            check_conversion(1.49);
        }
        SECTION("1.50") {
            check_conversion(1.50);
        }
        SECTION("1.51") {
            check_conversion(1.51);
        }
        SECTION("2.49") {
            check_conversion(2.49);
        }
        SECTION("2.50") {
            check_conversion(2.50);
        }
        SECTION("2.51") {
            check_conversion(2.51);
        }
        SECTION("1e30") {
            check_conversion(1e30);
        }
        SECTION("Inf") {
            check_conversion(std::numeric_limits<FromType>::infinity(), true);
        }
        SECTION("NaN") {
            check_conversion(std::numeric_limits<FromType>::quiet_NaN(), true);
        }
    }

    SECTION("negative") {
        SECTION("0.49") {
            check_conversion(-0.49);
        }
        SECTION("0.5") {
            check_conversion(-0.50);
        }
        SECTION("0.51") {
            check_conversion(-0.51);
        }
        SECTION("1.49") {
            check_conversion(-1.49);
        }
        SECTION("1.50") {
            check_conversion(-1.50);
        }
        SECTION("1.51") {
            check_conversion(-1.51);
        }
        SECTION("2.49") {
            check_conversion(-2.49);
        }
        SECTION("2.50") {
            check_conversion(-2.50);
        }
        SECTION("2.51") {
            check_conversion(-2.51);
        }
        SECTION("1e30") {
            check_conversion(-1e30);
        }
        SECTION("Inf") {
            check_conversion(-std::numeric_limits<FromType>::infinity(), true);
        }
        SECTION("NaN") {
            check_conversion(-std::numeric_limits<FromType>::quiet_NaN(), true);
        }
    }
}