name: ubuntu 22.04

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        cxx_standard: [20]
        build_type: ["Release", "Debug"]
        implicit_casts: ["ON", "OFF"]
        extensions: ["ON", "OFF"]
        sanitizers: ["ON", "OFF"]

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y build-essential ninja-build make zlib1g-dev wget \
        python3-pip python3 python3-dev python3-setuptools

        python3 -m pip install --upgrade pip
        python3 -m pip install --no-cache-dir "conan==2.20" cmake==3.30.0
        conan profile detect --force

    - name: Download dependencies
      run: |
        mkdir build && cd build
        cp ../conanfile.py .
        conan install . --build missing -s build_type=${{matrix.build_type}} -s compiler.cppstd=${{matrix.cxx_standard}}

    - name: Build
      env:
        CC: gcc
      run: |
        cd build
        cmake -G Ninja \
        -DCMAKE_TOOLCHAIN_FILE=./build/${{matrix.build_type}}/generators/conan_toolchain.cmake \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -DENABLE_IMPLICIT_CASTS=${{matrix.implicit_casts}} \
        -DENABLE_ASAN=${{matrix.sanitizers}} \
        -DCMAKE_CXX_EXTENSIONS=${{matrix.extensions}} \
        -DENABLE_TESTS=ON \
        ..
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest -C ${{matrix.build_type}} -V --output-on-failure
